### ISSUE TITLE
Build for F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [wtcounter/wtcounter#102] opened 2019-01-30 21:05 UTC
Attempts are being made to build this app for F-Droid, but some questions have arisen. Please, help out the packaging process at https://gitlab.com/fdroid/rfp/issues/605

**Comment by Bubu** [comment] 2019-07-31 15:17
Reproducible builds are now fixed by google in newer versions of the android gradle plugin.

You'll need to release a new version of this using the newest AGP version.

**Comment by IzzySoft** [comment] 2020-09-19 18:57
Speaking of which: While on Play we can find v4.4.1 dated 2020-07-04, last commit here was 2019-08-25 and the last tag is v3.0.3 from 2018-10-06. Is this app no longer open source – or did the repo move, @Apsaliya ?

**Comment by Apsaliya** [comment] 2021-08-21 07:48
I don't think F-Droid would be possible now as there are some closed source libraries being used in the app now. 

 @IzzySoft Apologies for super late reply. Yes this app is no longer open source. My ambition is to open source it again but there are some challenges . I haven't been able to work on this since long time but I'm reviving it again. Hopefully I'll be able to make it open source again.

**Closed as completed by Apsaliya** 2021-08-21 07:48 UTC

**Comment by IzzySoft** [comment] 2021-08-21 12:16
> Apologies for super late reply.

Better late than never :rofl:

> My ambition is to open source it again but there are some challenges .

Then my best wishes for overcoming them – sounds you already accepted the challenges, so there's some light on the horizont :smile: Be welcome to approach us again once you've reached that goal!
